# 

import os
from datetime import datetime, timezone
from typing import Literal

from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate


load_dotenv()


# ============================================================
# 1. STRUCTURED AI OUTPUT
# ============================================================

class CareAIOutput(BaseModel):
    """
    The part generated by Gemini.
    """

    quote: str = Field(
        description="A short, memorable plant-care quote."
    )

    care_tip: str = Field(
        description="A practical 1-3 sentence recommendation."
    )


# ============================================================
# 2. CREATE GEMINI MODEL
# ============================================================

def create_gemini_model():

    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY is missing from the .env file."
        )

    model_name = os.getenv(
        "GEMINI_MODEL",
        "gemini-2.5-flash"
    )

    model = ChatGoogleGenerativeAI(
        model=model_name,
        temperature=0.2,
        max_retries=2
    )

    return model


# ============================================================
# 3. NORMALIZE SENSOR DATA
# ============================================================

def normalize_sensor_data(sensor_data):
    """
    Accept both:

    A. Current local test format:
       {
           "plant": "Tomato",
           "soil_moisture": 18,
           "temperature": 31.5,
           "humidity": 55
       }

    B. Real GreenPulse MQTT format:
       {
           "device_id": "greenpulse-01",
           "seq": 1482,
           "ts": "...",
           "readings": {
               "soil_moisture_pct": 34.2,
               "soil_raw": 2210,
               "temperature_c": 29.8,
               "humidity_pct": 61.5
           },
           "fw": "1.0.3"
       }
    """

    # --------------------------------------------------------
    # Real MQTT format
    # --------------------------------------------------------

    if "readings" in sensor_data:

        readings = sensor_data["readings"]

        return {
            "device_id": sensor_data.get(
                "device_id",
                "greenpulse-01"
            ),
            "seq": sensor_data.get("seq"),
            "ts": sensor_data.get("ts"),
            "plant": sensor_data.get(
                "plant",
                "Unknown"
            ),
            "soil_moisture": readings.get(
                "soil_moisture_pct"
            ),
            "soil_raw": readings.get(
                "soil_raw"
            ),
            "temperature": readings.get(
                "temperature_c"
            ),
            "humidity": readings.get(
                "humidity_pct"
            )
        }

    # --------------------------------------------------------
    # Current local test format
    # --------------------------------------------------------

    return {
        "device_id": sensor_data.get(
            "device_id",
            "greenpulse-01"
        ),
        "seq": sensor_data.get("seq"),
        "ts": sensor_data.get("ts"),
        "plant": sensor_data.get(
            "plant",
            "Unknown"
        ),
        "soil_moisture": sensor_data.get(
            "soil_moisture"
        ),
        "soil_raw": sensor_data.get(
            "soil_raw"
        ),
        "temperature": sensor_data.get(
            "temperature"
        ),
        "humidity": sensor_data.get(
            "humidity"
        )
    }


# ============================================================
# 4. CALCULATE URGENCY
# ============================================================

def calculate_urgency(soil_moisture):

    if soil_moisture is None:

        return {
            "level": "amber",
            "score": 0.5,
            "next_water_eta_hours": None
        }

    # Conservative development thresholds.
    # These can later be tuned using the team's plant/history data.

    if soil_moisture < 20:

        return {
            "level": "red",
            "score": 0.90,
            "next_water_eta_hours": 2.0
        }

    elif soil_moisture < 35:

        return {
            "level": "amber",
            "score": 0.62,
            "next_water_eta_hours": 12.0
        }

    else:

        return {
            "level": "green",
            "score": 0.20,
            "next_water_eta_hours": None
        }


# ============================================================
# 5. MAIN CARE AGENT
# ============================================================

def care_agent(sensor_data):

    data = normalize_sensor_data(sensor_data)

    plant = data["plant"]
    soil_moisture = data["soil_moisture"]
    temperature = data["temperature"]
    humidity = data["humidity"]

    # --------------------------------------------------------
    # Validate critical sensor values
    # --------------------------------------------------------

    if soil_moisture is None:
        raise ValueError(
            "soil_moisture_pct is missing from the sensor reading."
        )

    # --------------------------------------------------------
    # Determine urgency independently
    # --------------------------------------------------------

    urgency = calculate_urgency(
        soil_moisture
    )

    # --------------------------------------------------------
    # Prompt Gemini
    # --------------------------------------------------------

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                """
You are the GreenPulse plant-care AI.

Your job is to generate a short, practical plant-care
recommendation from sensor readings.

Rules:

1. Use only the supplied sensor information.
2. Do not invent weather information.
3. Do not invent email information.
4. Soil moisture is the main watering signal.
5. Consider temperature and humidity as supporting conditions.
6. If soil moisture is very low, clearly recommend watering.
7. Keep the advice practical and conservative.
8. Do not diagnose plant diseases.
9. Return only the requested structured fields.
10. Write a short memorable quote and a useful care tip.
"""
            ),
            (
                "human",
                """
Plant: {plant}

Soil moisture: {soil_moisture}%
Temperature: {temperature}°C
Humidity: {humidity}%

Generate the GreenPulse care recommendation.
"""
            )
        ]
    )

    model = create_gemini_model()

    structured_model = model.with_structured_output(
        CareAIOutput,
        method="json_schema"
    )

    chain = prompt | structured_model

    result = chain.invoke(
        {
            "plant": plant,
            "soil_moisture": soil_moisture,
            "temperature": temperature,
            "humidity": humidity
        }
    )

    # --------------------------------------------------------
    # Timestamp
    # --------------------------------------------------------

    timestamp = data["ts"]

    if not timestamp:

        timestamp = (
            datetime.now(timezone.utc)
            .isoformat()
            .replace("+00:00", "Z")
        )

    # --------------------------------------------------------
    # MQTT /care payload
    # --------------------------------------------------------

    care_payload = {
        "device_id": data["device_id"],
        "ts": timestamp,
        "in_reply_to": data["seq"],
        "quote": result.quote,
        "care_tip": result.care_tip,
        "weather_summary": "",
        "inbox_summary": "",
        "agents": ["environment"],
        "model": os.getenv(
            "GEMINI_MODEL",
            "gemini-2.5-flash"
        )
    }

    # --------------------------------------------------------
    # MQTT /urgency payload
    # --------------------------------------------------------

    urgency_payload = {
        "device_id": data["device_id"],
        "ts": timestamp,
        "in_reply_to": data["seq"],
        "level": urgency["level"],
        "score": urgency["score"],
        "next_water_eta_hours": urgency[
            "next_water_eta_hours"
        ]
    }

    return {
        "urgency": urgency_payload,
        "care": care_payload
    }